"""Open the python interactive shell and do the following operations. The operands are 3 and 4.
addition(+)
subtraction(-)
multiplication(*)
modulus(%)
division(/)
exponential(**)
floor division operator(//)
"""
print(3+4)
print(3-4)
print(3*4)
print(3/4)
print(3//4)
print(3%4)
print(3**4)